---
kind: pipeline
name: s390x

platform:
  os: linux
  arch: amd64

node:
  arch: s390x

steps:
- name: build
  image: rancher/dapper:v0.5.8
  commands:
  - dapper ci
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: github_binary_release
  image: rancher/drone-images:github-release-s390x
  settings:
    api_key:
      from_secret: github_token
    prerelease: true
    checksum:
    - sha256
    checksum_file: CHECKSUMsum-s390x.txt
    checksum_flatten: true
    files:
    - "dist/artifacts/*"
  when:
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag